# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsAuth < Formula
  desc ""
  homepage "https://github.com/louislef299/aws-auth"
  version "1.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/louislef299/aws-auth/releases/download/v1.6.0/aws-auth_1.6.0_Darwin_arm64.tar.gz"
      sha256 "3dbb5773f784f99e60f9132c6a3280a01e268353f82d8ef4b5cce1d8a5fd0de3"

      def install
        bin.install "aws-auth"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/louislef299/aws-auth/releases/download/v1.6.0/aws-auth_1.6.0_Darwin_x86_64.tar.gz"
      sha256 "97ee4181b9c224e2017301e4cd8984e71f2def1b9fb71db347217dcee0f52288"

      def install
        bin.install "aws-auth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/louislef299/aws-auth/releases/download/v1.6.0/aws-auth_1.6.0_Linux_arm.tar.gz"
      sha256 "eb13d425db24405a0471d85f5b62ae1577c78a129959e9eeedb1475e8f31c6f3"

      def install
        bin.install "aws-auth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/louislef299/aws-auth/releases/download/v1.6.0/aws-auth_1.6.0_Linux_arm64.tar.gz"
      sha256 "ea39b018c6a3b4efd6884b5dc80f0b9dc7258d16e97c86d4256184c522b347f8"

      def install
        bin.install "aws-auth"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/louislef299/aws-auth/releases/download/v1.6.0/aws-auth_1.6.0_Linux_x86_64.tar.gz"
      sha256 "04b2faa00691621cfec5ae5a244fcd3245b1baf8c982761cce5859bbc3963efa"

      def install
        bin.install "aws-auth"
      end
    end
  end
end
