# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsLogin < Formula
  desc ""
  homepage "https://github.com/louislef299/aws-login"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/louislef299/aws-login/releases/download/v1.1.0/aws-login_1.1.0_Darwin_arm64.tar.gz"
      sha256 "28b59100817e250495ed25dc5c497c115e6c22fdc5cf31f245ad0d2ecc925a31"

      def install
        bin.install "aws-login"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/louislef299/aws-login/releases/download/v1.1.0/aws-login_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "b6a3ad6a04aed25094ba2b02a839d8e556aaf91000036d113cbf655babbde6c8"

      def install
        bin.install "aws-login"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/louislef299/aws-login/releases/download/v1.1.0/aws-login_1.1.0_Linux_arm.tar.gz"
      sha256 "746f24ecb40f6f80ee637259d83958abfee354b308bec466a3444afa0afdd2c8"

      def install
        bin.install "aws-login"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/louislef299/aws-login/releases/download/v1.1.0/aws-login_1.1.0_Linux_x86_64.tar.gz"
      sha256 "d9332d6ac0663941f35c121a51c6775f14dd68cbfe7dd8b2d4cfce6aca56d3e8"

      def install
        bin.install "aws-login"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/louislef299/aws-login/releases/download/v1.1.0/aws-login_1.1.0_Linux_arm64.tar.gz"
      sha256 "779910fa02fffaa5053d8ba77235b76f8104699cce8f340ea4f6f5c18cb9162e"

      def install
        bin.install "aws-login"
      end
    end
  end
end
