# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSso < Formula
  desc ""
  homepage "https://github.com/louislef299/aws-sso"
  version "1.4.27"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/louislef299/aws-sso/releases/download/v1.4.27/aws-sso_1.4.27_Darwin_x86_64.tar.gz"
      sha256 "2fc8c248d07cc5086b2fa9aa9014e0a83f6dd34438abd4eb34c54aa8e2060c1d"

      def install
        bin.install "aws-sso"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/louislef299/aws-sso/releases/download/v1.4.27/aws-sso_1.4.27_Darwin_arm64.tar.gz"
      sha256 "35dd83ea778d30da64912c82bb86443d3fe33a0c048191e2582a213aaea5da26"

      def install
        bin.install "aws-sso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/louislef299/aws-sso/releases/download/v1.4.27/aws-sso_1.4.27_Linux_x86_64.tar.gz"
      sha256 "0e86bdb8fe9f7f61d69197e357aa7436be770de8bda44edcb124af4eff0a0946"
      def install
        bin.install "aws-sso"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/louislef299/aws-sso/releases/download/v1.4.27/aws-sso_1.4.27_Linux_arm.tar.gz"
      sha256 "76048dfa3754230eb0af98a4ff10ee5ffeb2be7d95d8a9e69b3212f3ede8fb6e"
      def install
        bin.install "aws-sso"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/louislef299/aws-sso/releases/download/v1.4.27/aws-sso_1.4.27_Linux_arm64.tar.gz"
      sha256 "ffd33488016fc2c69472e4478f3c5f88e823bfa45055cf48e2d52751f01830d0"
      def install
        bin.install "aws-sso"
      end
    end
  end
end
