# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-sso" do
  version "1.6.24"

  on_macos do
    on_intel do
      sha256 "65f8029c2f37f6e7f653e82e0acb654903873aa496cffa8576a13d1033cf8aea"
      url "https://github.com/louislef299/aws-sso/releases/download/v#{version}/aws-sso_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4054927a24376930e8d15eae7f9440fa0468e6a214e2b251293cfb6d278e7991"
      url "https://github.com/louislef299/aws-sso/releases/download/v#{version}/aws-sso_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ef29e241d0380be7221654822935e56c05ab6bdc1af8c8965906e97d0e3a0cd"
      url "https://github.com/louislef299/aws-sso/releases/download/v#{version}/aws-sso_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c577470eaafec28aab3a4cca9416236b21d2d27a1545022a8cddf2d4893ced2e"
      url "https://github.com/louislef299/aws-sso/releases/download/v#{version}/aws-sso_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aws-sso"
  desc "Thanks for installing aws-sso! You can get configured by going to https://aws-sso.netlify.app. The binary you have installed came with a binary signature if you would like to verify the install. More information can be found on the website"
  homepage "https://github.com/louislef299/aws-sso"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-sso"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-sso"]
    end
  end

  # No zap stanza required

end
