# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-sso" do
  name "aws-sso"
  desc "Thanks for installing aws-sso! You can get configured by going to https://aws-sso.netlify.app. The binary you have installed came with a binary signature if you would like to verify the install. More information can be found on the website"
  homepage "https://github.com/louislef299/aws-sso"
  version "1.6.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-sso"

  on_macos do
    on_intel do
      url "https://github.com/louislef299/aws-sso/releases/download/v#{version}/aws-sso_#{version}_darwin_amd64.tar.gz"
      sha256 "13192675f0474d825f28f1d5c7ab986985cb1925ea10f8b75cc6c6b3d627700e"
    end
    on_arm do
      url "https://github.com/louislef299/aws-sso/releases/download/v#{version}/aws-sso_#{version}_darwin_arm64.tar.gz"
      sha256 "95ebd1c9fee3f29a03e70113446b32ba5fea615c2f4069e2620d5aaaf23960cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louislef299/aws-sso/releases/download/v#{version}/aws-sso_#{version}_linux_amd64.tar.gz"
      sha256 "e89771224fa82095d4c86c958ab647e4f747dea4432813f7d63c373ea41edf0f"
    end
    on_arm do
      url "https://github.com/louislef299/aws-sso/releases/download/v#{version}/aws-sso_#{version}_linux_arm64.tar.gz"
      sha256 "b33a41f2647f07d6b9408bfc8cd46a22ead941a41031393ef0f4fe48623b90e3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-sso"]
    end
  end

  # No zap stanza required
end
