# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-sso" do
  desc ""
  homepage "https://github.com/louislef299/aws-sso"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-sso"

  on_macos do
    on_intel do
      url "https://github.com/louislef299/aws-sso/releases/download/v1.5.0/aws-sso_1.5.0_Darwin_x86_64.tar.gz"
      sha256 "887fe6b05c9edc1074af0531ea6d88ed0e98997ed35fefa8c4c8a1f7018809c5"
    end
    on_arm do
      url "https://github.com/louislef299/aws-sso/releases/download/v1.5.0/aws-sso_1.5.0_Darwin_arm64.tar.gz"
      sha256 "d3b656c52bc1d9e287f3ed1e48c7a15098510aab0ecc1fa55f34723346906ea1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louislef299/aws-sso/releases/download/v1.5.0/aws-sso_1.5.0_Linux_x86_64.tar.gz"
      sha256 "c9b408946e5ac17c614bbf566266b0b842f3134e4ed2b1e9fd9d8e4437686901"
    end
    on_arm do
      url "https://github.com/louislef299/aws-sso/releases/download/v1.5.0/aws-sso_1.5.0_Linux_arm64.tar.gz"
      sha256 "6bcab63aa4a4c96deefd1935e917c026a258fe6ce35c16213485104ca921d9c6"
    end
  end

  # No zap stanza required
end
